language: cpp
compiler:
- g++
os:
- linux
before_install:
- ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -y
- sudo apt-get install g++-4.9 -y
script: make
