language: cpp
compiler:
- gcc
os:
- linux
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
install:
- sudo apt-get install gcc-4.8 -y
before_script:
- mkdir obj
script: make
