language: cpp
compiler:
- g++
os:
- linux
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
install:
- sudo apt-get install g++-4.8 -y
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
script: make
